name: Version Checker

on:
  pull_request:
    branches: 
      - master

jobs:
  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    steps:

      - name: Checkout pull request branch
        uses: actions/checkout@v2

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: ./master

      - name: Perform version check
        id: version_check
        uses: SubnauticaModding/Action-Version-Checker@master
        with:
          files: |
            SMLHelper/Properties/AssemblyInfo.cs | /\[assembly: Assembly(?:File)?Version\("([0-9.]+)"\)\]/g
            SMLHelper/mod_BelowZero.json         | /"Version": "([0-9.]+)",/g
            SMLHelper/mod_Subnautica.json        | /"Version": "([0-9.]+)",/g
          master_repo_path: ./master

      - name: Add annotations
        uses: Attest/annotations-action@v1.0.7
        with:
          path: ${{ steps.version_check.outputs.annotations_path }}
          title: Annotate
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Report status
        run: |
          if [[ -f ${{ steps.version_check.outputs.failed_check_path }} ]] ; then
              exit 1
          else
              exit 0
          fi
